# Sprint0 授業前課題
# 機械学習スクラッチ入門



## 【問題1】train_test_splitのスクラッチ

まずはスクラッチの練習として、scikit-learnのtrain_test_splitを自作してみましょう。Jupyter Notebookでコーディングを進め、完成後はpyファイルとします。utilsディレクトリの中にsplit.pyを作ってください。

[sklearn.model_selection.train_test_split — scikit-learn 0.20.0 documentation](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html)

In [26]:
#pyファイルを読み込むためにpathを追加

import numpy as np
import sys

#pathが直下に無いのでutilへのpathを追加
str = "/Users/ohmori/diveintocode-ml/diveintocode-term1/ml-scratch/utils"

#strがsys.pathになければ追加
if str not in sys.path:
    sys.path.append(str)

In [27]:
#path追加の確認
print(sys.path)

['/Users/ohmori/anaconda3/lib/python36.zip', '/Users/ohmori/anaconda3/lib/python3.6', '/Users/ohmori/anaconda3/lib/python3.6/lib-dynload', '', '/Users/ohmori/anaconda3/lib/python3.6/site-packages', '/Users/ohmori/anaconda3/lib/python3.6/site-packages/aeosa', '/Users/ohmori/anaconda3/lib/python3.6/site-packages/IPython/extensions', '/Users/ohmori/.ipython', '/Users/ohmori/diveintocode-ml/diveintocode-term1/ml-scratch/utils']


In [3]:
#split.pyからtrain_test_splitのmethodをimport 
from split import  train_test_split

作成したpyファイルは[こちら](https://github.com/ohmorimori/diveintocode-ml/blob/master/diveintocode-term1/ml-scratch/utils/split.py)

In [4]:
#動作確認
X = np.array([
    [1, 2],
    [3, 4],
    [5, 6],
    [7, 8]
])

y = np.array([1, 2, 3, 4])

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [6]:
print(X_train, '\n')
print(X_test, '\n')
print(y_train, '\n')
print(y_test, '\n')

[[3 4]
 [5 6]
 [7 8]] 

[[1 2]] 

[2 3 4] 

[1] 



## 【問題2】 分類パイプラインの作成

分類は3種類の手法を扱います。pyファイルで実行できる分類のパイプラインを作成してください。

* ロジスティック回帰<br>
* SVM<br>
* 決定木<br>

データセットは3種類用意します。

1つ目は事前学習期間同様にirisデータセットです。

[sklearn.datasets.load_iris — scikit-learn 0.20.2 documentation](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_iris.html)

2値分類としたいため、以下の2つの目的変数のみ利用します。特徴量は4種類全て使います。

* virgicolorとvirginica

また、残り2つは可視化が可能な特徴量が2つのデータセットを人工的に用意します。以下のコードで説明変数X,目的変数yが作成可能です。「シンプルデータセット1」「シンプルデータセット2」とします。

### Logistic Regression

#### Prepare Dataset

In [7]:
#read data

from sklearn.datasets import load_iris
dataset = load_iris()
print(dataset.keys())
print(dataset.target_names)

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])
['setosa' 'versicolor' 'virginica']


In [8]:
#split data

import pandas as pd
#import features
X = pd.DataFrame(dataset.data, columns = dataset.feature_names)

#import target value
y = pd.DataFrame(dataset.target, columns = {'species'})
print(X.head())
print(y.head())

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2
   species
0        0
1        0
2        0
3        0
4        0


In [9]:
#concatenate x and y
df = pd.concat((X, y), axis=1)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   species  
0        0  
1        0  
2        0  
3        0  
4        0

In [10]:
#extract only versicolor and virginica
#drop setosa rows(label: 0)

setosa_row = df[df['species'] == 0].index
df = df.drop(setosa_row, axis=0)

In [11]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
50                7.0               3.2                4.7               1.4   
51                6.4               3.2                4.5               1.5   
52                6.9               3.1                4.9               1.5   
53                5.5               2.3                4.0               1.3   
54                6.5               2.8                4.6               1.5   

    species  
50        1  
51        1  
52        1  
53        1  
54        1

In [12]:
from split import  train_test_split
#split arrays into two (train, test)
#shuffling is True by default
X_train, X_test, y_train, y_test = train_test_split(np.array(df.iloc[:, :4]), np.array(df.iloc[:, 4]), train_size=3/4)

In [13]:
#confirm if correctly split
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(75, 4)
(25, 4)
(75,)
(25,)


#### Fit, Estimate and Evaluate

pyファイルは[こちら](https://github.com/ohmorimori/diveintocode-ml/blob/master/diveintocode-term1/sprint/sprint0/modules/Classification.py)

In [14]:
#Regression.pyからLogisticRegressionをインポート
from modules.Classification import LogReg
#Regression.pyからSVClasisfierをインポート
from modules.Classification import SVClassifier
#Regression.pyからDecisionTreeClassifierをインポート
from modules.Classification import DTClassifier


LogReg(X_train, X_test, y_train, y_test);
SVClassifier(X_train, X_test, y_train, y_test);
DTClassifier(X_train, X_test, y_train, y_test);

              precision    recall  f1-score   support

           1       1.00      1.00      1.00        16
           2       1.00      1.00      1.00         9

   micro avg       1.00      1.00      1.00        25
   macro avg       1.00      1.00      1.00        25
weighted avg       1.00      1.00      1.00        25

              precision    recall  f1-score   support

           1       1.00      1.00      1.00        16
           2       1.00      1.00      1.00         9

   micro avg       1.00      1.00      1.00        25
   macro avg       1.00      1.00      1.00        25
weighted avg       1.00      1.00      1.00        25

              precision    recall  f1-score   support

           1       1.00      0.94      0.97        16
           2       0.90      1.00      0.95         9

   micro avg       0.96      0.96      0.96        25
   macro avg       0.95      0.97      0.96        25
weighted avg       0.96      0.96      0.96        25



/Users/ohmori/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


### SVM

#### Prepare Dataset

In [15]:
import numpy as np

np.random.seed(seed=0)
n_samples = 500
f0 = [-1, 2]
f1 = [2, -1]
cov = [[1.0,0.8], [0.8, 1.0]]

f0 = np.random.multivariate_normal(f0, cov, int(n_samples/2))
f1 = np.random.multivariate_normal(f1, cov, int(n_samples/2))

X = np.concatenate((f0, f1))
y = np.concatenate((np.ones((int(n_samples/2))), np.ones((int(n_samples/2))) *(-1))).astype(np.int)

random_index = np.random.permutation(np.arange(n_samples))
X = X[random_index]
y = y[random_index]

In [16]:
from split import  train_test_split
#split arrays into two (train, test)
#shuffling is True by default
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=3/4)

#### Fit, Estimate and Evaluate

In [17]:
LogReg(X_train, X_test, y_train, y_test);
SVClassifier(X_train, X_test, y_train, y_test);
DTClassifier(X_train, X_test, y_train, y_test);

              precision    recall  f1-score   support

          -1       1.00      1.00      1.00        58
           1       1.00      1.00      1.00        67

   micro avg       1.00      1.00      1.00       125
   macro avg       1.00      1.00      1.00       125
weighted avg       1.00      1.00      1.00       125

              precision    recall  f1-score   support

          -1       1.00      1.00      1.00        58
           1       1.00      1.00      1.00        67

   micro avg       1.00      1.00      1.00       125
   macro avg       1.00      1.00      1.00       125
weighted avg       1.00      1.00      1.00       125

              precision    recall  f1-score   support

          -1       1.00      1.00      1.00        58
           1       1.00      1.00      1.00        67

   micro avg       1.00      1.00      1.00       125
   macro avg       1.00      1.00      1.00       125
weighted avg       1.00      1.00      1.00       125



/Users/ohmori/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


### シンプルデータセット2

#### Prepare Dataset

In [18]:
X = np.array([[-0.44699 , -2.8073  ],[-1.4621  , -2.4586  ],
       [ 0.10645 ,  1.9242  ],[-3.5944  , -4.0112  ],
       [-0.9888  ,  4.5718  ],[-3.1625  , -3.9606  ],
       [ 0.56421 ,  0.72888 ],[-0.60216 ,  8.4636  ],
       [-0.61251 , -0.75345 ],[-0.73535 , -2.2718  ],
       [-0.80647 , -2.2135  ],[ 0.86291 ,  2.3946  ],
       [-3.1108  ,  0.15394 ],[-2.9362  ,  2.5462  ],
       [-0.57242 , -2.9915  ],[ 1.4771  ,  3.4896  ],
       [ 0.58619 ,  0.37158 ],[ 0.6017  ,  4.3439  ],
       [-2.1086  ,  8.3428  ],[-4.1013  , -4.353   ],
       [-1.9948  , -1.3927  ],[ 0.35084 , -0.031994],
       [ 0.96765 ,  7.8929  ],[-1.281   , 15.6824  ],
       [ 0.96765 , 10.083   ],[ 1.3763  ,  1.3347  ],
       [-2.234   , -2.5323  ],[-2.9452  , -1.8219  ],
       [ 0.14654 , -0.28733 ],[ 0.5461  ,  5.8245  ],
       [-0.65259 ,  9.3444  ],[ 0.59912 ,  5.3524  ],
       [ 0.50214 , -0.31818 ],[-3.0603  , -3.6461  ],
       [-6.6797  ,  0.67661 ],[-2.353   , -0.72261 ],
       [ 1.1319  ,  2.4023  ],[-0.12243 ,  9.0162  ],
       [-2.5677  , 13.1779  ],[ 0.057313,  5.4681  ]])
y = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [19]:
from split import  train_test_split
#split arrays into two (train, test)
#shuffling is True by default
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=3/4)

#### Fit, Estimate and Evaluate

In [20]:
LogReg(X_train, X_test, y_train, y_test);
SVClassifier(X_train, X_test, y_train, y_test);
DTClassifier(X_train, X_test, y_train, y_test);

              precision    recall  f1-score   support

           0       0.33      0.67      0.44         3
           1       0.75      0.43      0.55         7

   micro avg       0.50      0.50      0.50        10
   macro avg       0.54      0.55      0.49        10
weighted avg       0.62      0.50      0.52        10

              precision    recall  f1-score   support

           0       0.33      1.00      0.50         3
           1       1.00      0.14      0.25         7

   micro avg       0.40      0.40      0.40        10
   macro avg       0.67      0.57      0.38        10
weighted avg       0.80      0.40      0.33        10

              precision    recall  f1-score   support

           0       0.33      0.67      0.44         3
           1       0.75      0.43      0.55         7

   micro avg       0.50      0.50      0.50        10
   macro avg       0.54      0.55      0.49        10
weighted avg       0.62      0.50      0.52        10



/Users/ohmori/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


## 【問題3】 回帰パイプラインの作成
回帰は1種類を扱います。pyファイルで実行できる回帰のパイプラインを作成してください。

* 線形回帰

データセットは事前学習期間同様にHouse Pricesコンペティションのものを使います。

House Prices: Advanced Regression Techniques

train.csvをダウンロードし、目的変数としてSalePrice、説明変数として、GrLivAreaとYearBuiltを使います。

### House Pricesコンペティション

#### Prepare Dataset

In [21]:
#read data
import pandas as pd
import numpy as np

#read csv file to get data frame
df = pd.read_csv('train.csv')

#split into features X and target y
X = df.loc[:, ["YearBuilt", "GrLivArea"]]
df['SalePriceLog'] = np.log(df["SalePrice"])
y = df.loc[:, ['SalePriceLog']]

In [22]:
#confirm datra
print(X.head(), "\n")
print(y.head())

   YearBuilt  GrLivArea
0       2003       1710
1       1976       1262
2       2001       1786
3       1915       1717
4       2000       2198 

   SalePriceLog
0     12.247694
1     12.109011
2     12.317167
3     11.849398
4     12.429216


In [23]:
#Split into train and test data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=3/4, test_size=1/4)

#### Fit, Estimate and Evaluate

pyファイルは[こちら](https://github.com/ohmorimori/diveintocode-ml/blob/master/diveintocode-term1/sprint/sprint0/modules/Regression.py)

In [24]:
#Regression.pyからLinearRegをインポート
from modules.Regression import LinearReg

LinearReg(X_train, X_test, y_train, y_test);

Score R^2 0.6893987992204424


/Users/ohmori/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/data.py:645: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
/Users/ohmori/anaconda3/lib/python3.6/site-packages/sklearn/base.py:467: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.fit(X, y, **fit_params).transform(X)
/Users/ohmori/anaconda3/lib/python3.6/site-packages/sklearn/pipeline.py:331: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  Xt = transform.transform(Xt)
/Users/ohmori/anaconda3/lib/python3.6/site-packages/sklearn/pipeline.py:511: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  Xt = transform.transform(Xt)
