# Week2授業前課題3
## 【課題1】内積を手計算しよう
___

$$
A=
\begin{bmatrix}
-1&2&3\\
4&-5&6\\
7&8&-9
\end{bmatrix}
,B=
\begin{bmatrix}
0&2&1\\
0&2&-8\\
2&9&-1
\end{bmatrix}
$$  
$$
AB =
\begin{bmatrix}
6 &29&-20\\
12&52&38\\
-18&-51&-48
\end{bmatrix}
$$

## 【課題2】1次元配列の内積をfor文で計算しよう
___

In [56]:
import numpy as np
A1 = np.array([
    [-1, 2, 3]
])

B1 = np.array([
    [0],
    [0],
    [2]
])

In [47]:
s = 0
for j in range (B1.shape[0]):
    s += A1[0, j] *B1[j,0]
print(s)

6


## 【課題3】多次元配列の内積をfor文で計算しよう
___

In [57]:
A2 = np.array([
    [-1, 2, 3],
    [4, -5, 6],
    [7, 8, -9]
])

B2 =np.array([
    [0, 2, 1],
    [0, 2, -8],
    [2, 9, -1]
])

In [58]:
def matrix_product(A, B):
    C = np.full((A.shape[1], B.shape[0]), 0)
    if (A.shape[1] != B.shape[0]):
        print("Unable to calculate")
        return
    for i in range (A.shape[0]):
        for j in range (B.shape[1]):
            s = 0
            for k in range(B.shape[0]):
                s += A[i, k] *B[k, j]
            C[i, j] = s
    return C

In [59]:
C = matrix_product(A2, B2)
print(C)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


## 【課題4】内積をnp.dotで計算しよう
___

In [61]:
C = np.dot(A2, B2)
print(C)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


## 【課題5】内積ができないときはどうするか
___

$$
A=
\begin{bmatrix}
a&2&3\\
4&-5&6
\end{bmatrix}
,
B =
\begin{bmatrix}
-9&8&7\\
6&-5&4
\end{bmatrix}
$$

In [73]:
A3 = np.array([
    [-1, 2, 3],
    [4, -5, 6]
])

B3 = np.array([
    [-9, 8, 7],
    [6, -5, 4]
])

エラーが出る理由：  
２つの行列A, Bの積ABを計算するには、Aの列数とBの行数が一致している必要があるため。つまり、AとBのサイズを表した時に(i, k), (k, j)のようにkが一致していることが積を計算できる条件だが、(2,3) ,  (2,3)だと一致していないので計算できない。 

In [70]:
C = np.dot(A3, B3)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

行列A, Bのどちらかの転置行列を取れば、(2, 3), (3, 2)もしくは(3, 2), (2, 3)となり、kが一致するため積を計算できる。サイズ(i, k), (k, j)の２つの行列の積の結果として得られる行列のサイズは(i, j)となる。

In [76]:
A4 = A3
B4 = B3.transpose()

In [75]:
C = np.dot(A4, B4)
print(C)

[[ 46  -4]
 [-34  73]]
