# Week4授業前課題3 オブジェクト指向に慣れよう

## 【問題1】これまで利用してきたクラスの列挙
クラスを使う際はインスタンス化を行うことと、クラスの命名法がわかりました。この情報を元に、これまでの課題で利用してきたコードの中でどのようなクラスがあったかを答えてください。

最低でもPandas、matplotlib、scikit-learnからそれぞれ1つ以上見つけてください。

メソッド
インスタンス化を行った後には、scaler.fit(X)のような メソッド の実行がきます。StandardScalerのfitメソッドは後でスケーリングに使われる平均と標準偏差を計算する機能があります。

インスタンス変数（アトリビュート）
fitメソッドにより平均と標準偏差が計算されましたが、見た目には変化があるわけではありません。しかし、scalerインスタンスの内部では計算結果が保存されています。こういったインスタンスの中で値を保存するものを インスタンス変数 や アトリビュート（属性） と呼びます。ここで平均がscaler.mean_、標準偏差の2乗した値である分散がscaler.var_に保存されています。

|ライブラリ|クラスの例|
|:--|:--|
|pandas|DataFrame|
|matplotlib|ListedColormap|
|scikit-learn|LogisticRegression, SVC, KNeighborsClassifier|

## 【問題2】これまで利用してきたメソッドやインスタンス変数の列挙
これまでの課題で利用してきたコードの中でどのようなメソッドやインスタンス変数があったかを答えてください。

最低でもそれぞれ5つ以上答えてください。

ndarrayやstrもインスタンス

ドットをつけるというと、NumPyのndarrayに対してndarray.shapeやndarray.sum()のような使い方は何度も利用してきたかと思います。これは、ndarrayもインスタンスオブジェクトであり、shapeはインスタンス変数、sumはメソッドだったということです。

Pythonのコードに登場するデータはどれもインスタンスオブジェクトであり、listやstrもメソッドを持ちます。

|クラス|インスタンス変数の例|メソッドの例|
|:--|:--|:--|
|DataFrame|dtypes, shape, describe, index, columns|head, tail, drop, |
|KNeighborsClassifier|mean_|fit, predict|




## 【問題3】標準化クラスをスクラッチで作成
理解をより深めるため、StandardScalerをスクラッチで作成しましょう。scikit-learnは使わず、NumPyなどを活用して標準化の計算を記述します。具体的にはfitメソッドとtransformメソッドを作ります。

今回は雛形を用意しました。クラスの作成方法は関数に近いです。メソッドはクラスの中にさらにインデントを一段下げて記述します。

インスタンス変数を作成する際はself.mean_のようにselfを付けます。クラスの外からscaler.mean_と書いていたscalerの部分が自分自身を表すselfになっています。

In [24]:
import numpy as np
class ScratchStandardScaler():
    """
    標準化のためのクラス

    Attributes
    ----------
    mean_ : 次の形のndarray, shape(n_features,)
        平均
    var_ : 次の形のndarray, shape(n_features,)
        分散
    """

    def fit(self, X):
        """
        標準化のために平均と標準偏差を計算する。

        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            学習データ
        """
        #平均値
        self.mean_ = X.mean(axis=0)
        #分散
        self.var_ = X.var(axis=0)
        #標準偏差
        self.std_ = X.std(axis=0)

        pass

    def transform(self, X):
        """
        fitで求めた値を使い標準化を行う。

        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            特徴量

        Returns
        ----------
        X_scaled : 次の形のndarray, shape (n_samples, n_features)
            標準化された特緒量
        """
        
        X_scaled = (X - self.mean_)/self.std_
        
        pass
        return X_scaled

In [345]:
#実行するコード
import numpy as np
from sklearn.datasets import load_iris

data = load_iris()
X = data.data[:10]

scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print("平均 :", scratch_scaler.mean_)
print("分散 :", scratch_scaler.var_)
X_std = scratch_scaler.transform(X)
print("Normalize後のX\n", X_std)

平均 : [4.86 3.31 1.45 0.22]
分散 : [0.0764 0.0849 0.0105 0.0056]
Normalize後のX
 [[ 0.86828953  0.65207831 -0.48795004 -0.26726124]
 [ 0.14471492 -1.06391725 -0.48795004 -0.26726124]
 [-0.57885968 -0.37751902 -1.46385011 -0.26726124]
 [-0.94064699 -0.72071813  0.48795004 -0.26726124]
 [ 0.50650222  0.99527742 -0.48795004 -0.26726124]
 [ 1.95365143  2.02487476  2.43975018  2.40535118]
 [-0.94064699  0.3088792  -0.48795004  1.06904497]
 [ 0.50650222  0.3088792   0.48795004 -0.26726124]
 [-1.66422159 -1.40711636 -0.48795004 -0.26726124]
 [ 0.14471492 -0.72071813  0.48795004 -1.60356745]]


## 【課題4】 四則演算を行うクラスの作成
下記ExampleClassは足し算のメソッドを持っていますが、これに引き算、掛け算、割り算のメソッドを加えてください。

また、コンストラクタに入力されたvalueが文字列や配列など数値以外だった場合には警告文を出し、self.value=0とするコードを追加してください。

クラス名や説明文も適切に書き換えてください。

In [335]:
from functools import wraps

class CalculateValue():
    """
    説明用の簡単なクラス

    Parameters
    ----------
    value : float or int
        初期値

    Attributes
    ----------
    value : float or int
        計算結果
    """
    
    #Constructor
    def __init__(self, value_):
        #引数がint or floatの時のみインスタンス変数として受け取る
        if (isinstance(value_, int) or isinstance(value_, float)):
            self.value = value_
        #引数の型がint or float以外の時はインスタンス変数にゼロを代入
        else:
            self.value = 0
            print('\n初期化のために渡された引数が数値でないので、ゼロで初期化します')

        print("初期値{}が設定されました".format(self.value))
    
    #計算のための引数がint or floatの時のみ計算するようなコールバック関数
    #メソッドを引数として受け取って処理する
    def check_argument_type(fn):
        @wraps(fn)
        def wrapper(self, value_):
            #引数がint or floatの時
            if (isinstance(value_, int) or isinstance(value_, float)):
                #引数として受け取ったメソッドを実行
                fn(self, value_)
            #引数がint or float以外の時
            else:
                #引数として受け取ったメソッドを実行せずに流す
                print('渡された引数が数値でないので計算をスキップしました')            
        return wrapper

    #printのためのメソッド
    def print_value(self):
        print("value :", self.value)

    #四則演算のメソッド
    #計算の前に引数の型チェックを入れる
    @check_argument_type    
    def add(self, value_):
        
        """
        受け取った引数をself.valueに加える
        """
        self.value += value_
        self.print_value()

    @check_argument_type
    def subtract(self, value_):
        self.value -= value_
        self.print_value()

    @check_argument_type
    def multiply(self, value_):
        self.value *= value_
        self.print_value()

    @check_argument_type
    def divide(self, value_):
        #引数が0以外の場合のみに計算を実行
        if (value_ != 0):
            self.value /= value_
            self.print_value()
        else:
            print("0で割ることはできません。計算をスキップしました。")

In [336]:
#intで初期化した場合
example = CalculateValue(5)
example.add(3)
example.subtract(1)
example.multiply(2)
example.divide(7)
#ゼロで割った場合
example.divide(0)

初期値5が設定されました
value : 8
value : 7
value : 14
value : 2.0
0で割ることはできません。計算をスキップしました。


In [337]:
#floatで初期化した場合
example = CalculateValue(5.2)
example.add(3)

初期値5.2が設定されました
value : 8.2


In [338]:
# strで初期化した場合
example = CalculateValue('moji')
example.add(3)


初期化のために渡された引数が数値でないので、ゼロで初期化します
初期値0が設定されました
value : 3


In [339]:
#strを演算の引数として渡した場合
example = CalculateValue(1)
example.add('str')
example.add(1)

初期値1が設定されました
渡された引数が数値でないので計算をスキップしました
value : 2
